app = "luluj2024-expense-web"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    API_URL = "https://luluj2024-expense-api.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
