name: CI
on:
  push:
  pull_request:

jobs:
  test-backend:
    name: Backend (Vitest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - run: npm ci
      - run: npm test -- --run

  build-frontend:
    name: Frontend (Vite build)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/expense-tracker   
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/expense-tracker/package-lock.json
      - run: npm ci
      
      - run: echo "VITE_API_URL=http://localhost:8080" > .env
      - run: npm run build
